services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: momo-store-frontend:latest
    container_name: momo-store-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - momo-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    read_only: true
    volumes:
      - nginx-cache:/var/cache/nginx:rw
      - nginx-pid:/var/run:rw

networks:
  momo-network:
    driver: bridge

volumes:
  nginx-cache:
  nginx-pid:
