name: Развертывание Docker-проекта

on:
  push:
    branches:
      - main

jobs:
  build_and_scan_backend:
    name: Сборка и сканирование бэкенда
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка образа бэкенда
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: false
          load: true
          tags: docker-project-backend:latest

      - name: Запуск Trivy для бэкенда
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build_and_scan_frontend:
    name: Сборка и сканирование фронтенда
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Сборка образа фронтенда
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: false
          load: true
          tags: docker-project-frontend:latest

      - name: Запуск Trivy для фронтенда
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker-project-frontend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  push_to_docker_hub:
    name: Публикация образов в Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_scan_backend, build_and_scan_frontend]
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Пуш бэкенд-образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-backend:latest

      - name: Пуш фронтенд-образа в Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-project-frontend:latest

  run_with_docker_compose:
    name: Запуск через Docker Compose
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Сборка и запуск через Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          up-flags: "--build"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
